xpath:
  currency_row: .//tbody[@class="sort_body"]/tr[contains(@class, "c-currency-table__main-row")]
currency_url: https://myfin.by/currency/
headers: "{\
  'authority': 'myfin.by', \
  'cache-control': 'max-age=0', \
  'sec-ch-ua': '\" Not A;Brand\";v=\"99\", \"Chromium\";v=\"99\", \"Google Chrome\";v=\"99\"', \
  'sec-ch-ua-mobile': '?0', \
  'sec-ch-ua-platform': '\"Windows\"', \
  'upgrade-insecure-requests': '1', \
  'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.82 Safari/537.36', \
  'accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9', \
  'sec-fetch-site': 'same-origin', \
  'sec-fetch-mode': 'navigate', \
  'sec-fetch-user': '?1', \
  'sec-fetch-dest': 'document', \
  'referer': 'https://myfin.by/currency/minsk', \
  'accept-language': 'en-US,en;q=0.9,ru-RU;q=0.8,ru;q=0.7' \
  }"
proxy:
  enabled: false
  ip: 0.0.0.0
  port: 0
  login: login
  password: password
bot:
  nickname: DVAAAT_BOT
  token: 5243615972:AAGbTvriVVVgmWuZS-RdyA2i8yOWSt4TjXo
spring:
  devtools:
    add-properties: false
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false
  datasource:
    url: jdbc:postgresql://localhost:5432/currencybot
    username: currencybotuser
    password: currencybotuserpassword
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,beans
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
