apiVersion: 1

datasources:
  - name: Prometheus
    label: Prometheus
    type: prometheus
    access: proxy
    url: http://localhost:9090
    isDefault: false
    editable: true
  - name: Loki
    label: Loki
    type: loki
    access: proxy
    url: http://localhost:3100
    isDefault: false
    editable: true
