--
-- PostgreSQL database dump
--

-- Dumped from database version 14.3 (Debian 14.3-1.pgdg110+1)
-- Dumped by pg_dump version 14.3 (Debian 14.3-1.pgdg110+1)

CREATE DATABASE currencybot;

ALTER DATABASE currencybot OWNER TO currencybotuser;

\connect currencybot

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: banks; Type: TABLE; Schema: public; Owner: currencybotuser
--

CREATE TABLE public.banks (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    type character varying(255) NOT NULL
);


ALTER TABLE public.banks OWNER TO currencybotuser;

--
-- Name: banks_id_seq; Type: SEQUENCE; Schema: public; Owner: currencybotuser
--

ALTER TABLE public.banks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.banks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: currencies; Type: TABLE; Schema: public; Owner: currencybotuser
--

CREATE TABLE public.currencies (
    id bigint NOT NULL,
    code character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    units integer NOT NULL
);


ALTER TABLE public.currencies OWNER TO currencybotuser;

--
-- Name: currencies_id_seq; Type: SEQUENCE; Schema: public; Owner: currencybotuser
--

ALTER TABLE public.currencies ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.currencies_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: exchange_rates; Type: TABLE; Schema: public; Owner: currencybotuser
--

CREATE TABLE public.exchange_rates (
    id bigint NOT NULL,
    purchase double precision NOT NULL,
    sale double precision NOT NULL,
    update_date timestamp without time zone NOT NULL,
    bank_id bigint NOT NULL,
    currency_id bigint NOT NULL
);


ALTER TABLE public.exchange_rates OWNER TO currencybotuser;

--
-- Name: exchange_rates_id_seq; Type: SEQUENCE; Schema: public; Owner: currencybotuser
--

ALTER TABLE public.exchange_rates ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.exchange_rates_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: nb_exchange_rates; Type: TABLE; Schema: public; Owner: currencybotuser
--

CREATE TABLE public.nb_exchange_rates (
    id bigint NOT NULL,
    current_rate double precision NOT NULL,
    tomorrow_rate double precision NOT NULL,
    update_date timestamp without time zone NOT NULL,
    currency_id bigint NOT NULL
);


ALTER TABLE public.nb_exchange_rates OWNER TO currencybotuser;

--
-- Name: nb_exchange_rates_id_seq; Type: SEQUENCE; Schema: public; Owner: currencybotuser
--

ALTER TABLE public.nb_exchange_rates ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.nb_exchange_rates_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: currencybotuser
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    chat_id character varying(255) NOT NULL,
    role character varying(255) NOT NULL,
    update_date timestamp without time zone NOT NULL
);


ALTER TABLE public.users OWNER TO currencybotuser;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: currencybotuser
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: banks; Type: TABLE DATA; Schema: public; Owner: currencybotuser
--

COPY public.banks (id, name, type) FROM stdin;
1	imbanking.by	INTERNET_BANKING
2	Paritetbank	DEPARTMENT
3	InSync by Alfa-Bank	INTERNET_BANKING
4	Абсолютбанк	DEPARTMENT
5	Альфа-Банк	DEPARTMENT
6	Банк БелВЭБ	DEPARTMENT
7	Банк ВТБ (Беларусь)	DEPARTMENT
8	Банк Дабрабыт	DEPARTMENT
9	Банк Решение	DEPARTMENT
10	Белагропромбанк	DEPARTMENT
11	Беларусбанк	DEPARTMENT
12	Белгазпромбанк	DEPARTMENT
13	Белинвестбанк	DEPARTMENT
14	БНБ-Банк	DEPARTMENT
15	БСБ Банк	DEPARTMENT
16	БТА Банк	DEPARTMENT
17	МТБанк	DEPARTMENT
18	Паритетбанк	DEPARTMENT
19	Приорбанк	DEPARTMENT
20	РРБ-Банк	DEPARTMENT
21	Сбер Банк	DEPARTMENT
22	СтатусБанк	DEPARTMENT
23	Технобанк	DEPARTMENT
24	ТК Банк	DEPARTMENT
25	Цептер Банк	DEPARTMENT
\.


--
-- Data for Name: currencies; Type: TABLE DATA; Schema: public; Owner: currencybotuser
--

COPY public.currencies (id, code, name, units) FROM stdin;
1	USD	Доллар США	1
2	EUR	Евро	1
3	RUB	Российский рубль	100
\.


--
-- Data for Name: nb_exchange_rates; Type: TABLE DATA; Schema: public; Owner: currencybotuser
--

COPY public.nb_exchange_rates (id, current_rate, tomorrow_rate, update_date, currency_id) FROM stdin;
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: currencybotuser
--

COPY public.users (id, chat_id, role, update_date) FROM stdin;
\.


--
-- Name: banks_id_seq; Type: SEQUENCE SET; Schema: public; Owner: currencybotuser
--

SELECT pg_catalog.setval('public.banks_id_seq', 25, true);


--
-- Name: currencies_id_seq; Type: SEQUENCE SET; Schema: public; Owner: currencybotuser
--

SELECT pg_catalog.setval('public.currencies_id_seq', 3, true);


--
-- Name: exchange_rates_id_seq; Type: SEQUENCE SET; Schema: public; Owner: currencybotuser
--

SELECT pg_catalog.setval('public.exchange_rates_id_seq', 1, false);


--
-- Name: nb_exchange_rates_id_seq; Type: SEQUENCE SET; Schema: public; Owner: currencybotuser
--

SELECT pg_catalog.setval('public.nb_exchange_rates_id_seq', 1, false);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: currencybotuser
--

SELECT pg_catalog.setval('public.users_id_seq', 1, false);


--
-- Name: banks banks_pkey; Type: CONSTRAINT; Schema: public; Owner: currencybotuser
--

ALTER TABLE ONLY public.banks
    ADD CONSTRAINT banks_pkey PRIMARY KEY (id);


--
-- Name: currencies currencies_pkey; Type: CONSTRAINT; Schema: public; Owner: currencybotuser
--

ALTER TABLE ONLY public.currencies
    ADD CONSTRAINT currencies_pkey PRIMARY KEY (id);


--
-- Name: exchange_rates exchange_rates_pkey; Type: CONSTRAINT; Schema: public; Owner: currencybotuser
--

ALTER TABLE ONLY public.exchange_rates
    ADD CONSTRAINT exchange_rates_pkey PRIMARY KEY (id);


--
-- Name: nb_exchange_rates nb_exchange_rates_pkey; Type: CONSTRAINT; Schema: public; Owner: currencybotuser
--

ALTER TABLE ONLY public.nb_exchange_rates
    ADD CONSTRAINT nb_exchange_rates_pkey PRIMARY KEY (id);


--
-- Name: currencies uk_5r2dfxl1m7vus47ma0y05sflt; Type: CONSTRAINT; Schema: public; Owner: currencybotuser
--

ALTER TABLE ONLY public.currencies
    ADD CONSTRAINT uk_5r2dfxl1m7vus47ma0y05sflt UNIQUE (code);


--
-- Name: currencies uk_a2yxotynwqjrmkq71won77vui; Type: CONSTRAINT; Schema: public; Owner: currencybotuser
--

ALTER TABLE ONLY public.currencies
    ADD CONSTRAINT uk_a2yxotynwqjrmkq71won77vui UNIQUE (name);


--
-- Name: banks uk_gfnfs2s5a771weqm28yvb2h5; Type: CONSTRAINT; Schema: public; Owner: currencybotuser
--

ALTER TABLE ONLY public.banks
    ADD CONSTRAINT uk_gfnfs2s5a771weqm28yvb2h5 UNIQUE (name);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: currencybotuser
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: bank_idx; Type: INDEX; Schema: public; Owner: currencybotuser
--

CREATE INDEX bank_idx ON public.banks USING btree (id, name);


--
-- Name: currency_idx; Type: INDEX; Schema: public; Owner: currencybotuser
--

CREATE INDEX currency_idx ON public.currencies USING btree (id, code);


--
-- Name: exchange_rate_idx; Type: INDEX; Schema: public; Owner: currencybotuser
--

CREATE INDEX exchange_rate_idx ON public.exchange_rates USING btree (id, bank_id, currency_id, update_date);


--
-- Name: nb_exchange_rate_idx; Type: INDEX; Schema: public; Owner: currencybotuser
--

CREATE INDEX nb_exchange_rate_idx ON public.nb_exchange_rates USING btree (id, currency_id, update_date);


--
-- Name: user_idx; Type: INDEX; Schema: public; Owner: currencybotuser
--

CREATE INDEX user_idx ON public.users USING btree (id, chat_id);


--
-- Name: exchange_rates fk7s6ao9nt17i1e73q5mq37he2v; Type: FK CONSTRAINT; Schema: public; Owner: currencybotuser
--

ALTER TABLE ONLY public.exchange_rates
    ADD CONSTRAINT fk7s6ao9nt17i1e73q5mq37he2v FOREIGN KEY (bank_id) REFERENCES public.banks(id);


--
-- Name: nb_exchange_rates fkeq4n7mwa8x617vw0rdc5ixtp; Type: FK CONSTRAINT; Schema: public; Owner: currencybotuser
--

ALTER TABLE ONLY public.nb_exchange_rates
    ADD CONSTRAINT fkeq4n7mwa8x617vw0rdc5ixtp FOREIGN KEY (currency_id) REFERENCES public.currencies(id);


--
-- Name: exchange_rates fkeqji20u77aqdsicuxscbe8pue; Type: FK CONSTRAINT; Schema: public; Owner: currencybotuser
--

ALTER TABLE ONLY public.exchange_rates
    ADD CONSTRAINT fkeqji20u77aqdsicuxscbe8pue FOREIGN KEY (currency_id) REFERENCES public.currencies(id);


--
-- PostgreSQL database dump complete
--